# Generated by Django 5.1.2 on 2024-10-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_amount',
            new_name='user_cash',
        ),
    ]
