# Generated by Django 5.1.2 on 2024-10-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=100),
        ),
    ]
