# Generated by Django 5.1.2 on 2024-10-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_bill_bill_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
