# Generated by Django 5.1.2 on 2024-10-23 12:51

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonepe',
            name='amount',
            field=models.FloatField(default=builtins.print),
            preserve_default=False,
        ),
    ]
