# Generated by Django 5.1.2 on 2024-10-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_phonepe_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phonepe',
        ),
    ]
