# Generated by Django 5.1.2 on 2024-10-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_phonepe_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonepe',
            name='amount',
        ),
    ]
