# Generated by Django 5.1.2 on 2024-10-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_phonepe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonepe',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
