# Generated by Django 5.1.2 on 2024-10-24 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_bank_account_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_verify_status', models.IntegerField(default=0)),
                ('office_verify_status', models.IntegerField(default=0)),
                ('admin_verify_status', models.IntegerField(default=0)),
                ('payment_type', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.bill')),
                ('phonepe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.phonepe')),
            ],
        ),
    ]
