# Generated by Django 5.1.2 on 2024-10-24 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_rename_phonepe_bank_transition_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_transition',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.bank_account'),
        ),
    ]
