# Generated by Django 5.1.2 on 2024-10-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_bank_transition_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='admin_verify_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='office_verify_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pending_amount_status',
            field=models.IntegerField(default=1),
        ),
    ]
