# Generated by Django 5.1.2 on 2024-10-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_out_phonepe_transition'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_out_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_bill_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('self_verify_status', models.IntegerField(default=0)),
                ('office_verify_status', models.IntegerField(default=0)),
                ('admin_verify_status', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.bank_account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
