# Generated by Django 5.1.2 on 2024-10-26 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_bank_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_transfer_to_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('self_verify_status', models.IntegerField(default=0)),
                ('office_verify_status', models.IntegerField(default=0)),
                ('admin_verify_status', models.IntegerField(default=0)),
                ('to_verify_status', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('to_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.bank_account')),
            ],
        ),
    ]
